Update JenkinsFile

diff --git a/JenkinsFile b/JenkinsFile
--- a/JenkinsFile
+++ b/JenkinsFile
@@ -1,30 +1,77 @@
 pipeline {
     agent any
+<<<<<<< HEAD
+
+    environment {
+        BUILD_DIR = "build"
+        APP_NAME = "app"
+    }
+=======
+>>>>>>> 150058cdcca0b15f8143e9d8e91794031042652e
     stages {
-        stage('Clone Repo') {
+        stage('Clone Repository') {
             steps {
+                git 'https://github.com/Vinaybt/Jenkins-Pipeline.git'
+            }
+        }
+        stage('Install Dependencies') {
+            steps {
+<<<<<<< HEAD
+                sh '''
+                    echo "[INFO] installing build tools..."
+                    apt-get update && apt-get install -y build-essential
+                '''
+=======
                 git branch: 'main', url: 'https://github.com/Vinaybt/Jenkins-Pipeline.git'
+>>>>>>> 150058cdcca0b15f8143e9d8e91794031042652e
             }
         }
-        stage('Build C++ App') {
+        stage('Build Application') {
             steps {
-                sh 'make'
+                sh '''
+                    echo "[INFO] Building C++ Application"
+                    mkdir -p ${BUILD_DIR}
+                    g++ -o ${BUILD_DIR}/{APP_NAME} main.cpp
+                    echo "Build Successful"
+                '''
             }
         }
-        stage('Run App') {
+        stage('Run Tests') {
             steps {
-                sh './app'
+                sh '''
+                    echo "[INFO] Running Tests..."
+                    # simulate a test
+                    if [ -f ${BUILD_DIR}/{APP_NAME} ]: then
+                        echo "[TEST PASSED] Binary exists"
+                    else 
+                        echo "[TEST FAILED] Binary missing"
+                        exit 1
+                    fi
+                '''
             }
         }
-        stage('Clean Up') {
+        stage('Deploy') {
             steps {
-                sh 'make clean'
+                sh '''
+                    echo "[INFO] Deploying to /tmp/deployment-folder..."
+                    mkdir -p /tmp/deployment-folder
+                    cp ${BUILD_DIR}/{APP_NAME} /tmp/deployment-folder/
+                    echo "[INFO] Deployment Successful"
+                '''
             }
         }
         stage('Archive Artifacts') {
             steps {
                 archiveArtifacts artifacts: '**/app', fingerprint: true
             }
+        }
+    }
+    post {
+        success {
+            echo "[SUCCESS] Build and deployment succeeded."
+        }
+        failure {
+            echo "[FAILED] Something went wrong."
         }
     }
 }
